import { CartManager } from './core/CartManager';
import { LocationManager } from './core/LocationManager';
import { BloggerDataService } from './infrastructure/BloggerDataService';
import { GooglePayService } from './infrastructure/GooglePayService';
import { ProductRenderer } from './presentation/ProductRenderer';
import { CartRenderer } from './presentation/CartRenderer';
import { LocationRenderer } from './presentation/LocationRenderer';
import { GeoVerificationRenderer } from './presentation/GeoVerificationRenderer';
import { OrderSummaryRenderer } from './presentation/OrderSummaryRenderer';
import { PhoneVerificationRenderer } from './presentation/PhoneVerificationRenderer';
import { SearchAutocompleteRenderer } from './presentation/SearchAutocompleteRenderer';
export declare class App {
    private state;
    private gridPageSize;
    private gridStartIndex;
    private currentLabels;
    private currentSearchQuery;
    private displaySearchQuery;
    private searchKeywordsOnly;
    CartManager: CartManager;
    LocationManager: LocationManager;
    BloggerDataService: BloggerDataService;
    GooglePayService: GooglePayService;
    ProductRenderer: ProductRenderer;
    CartRenderer: CartRenderer;
    LocationRenderer: LocationRenderer;
    GeoVerificationRenderer: GeoVerificationRenderer;
    OrderSummaryRenderer: OrderSummaryRenderer;
    PhoneVerificationRenderer: PhoneVerificationRenderer;
    SearchAutocompleteRenderer?: SearchAutocompleteRenderer;
    constructor();
    private detectContext;
    private formatLocationQuery;
    private exposeGlobals;
    private init;
    private initSearchInput;
    private updateCategoryLinks;
    private highlightActiveLabels;
    private setupEventListeners;
    private loadProductData;
    private loadGridData;
    loadMorePosts(): Promise<void>;
    private renderEntriesToGrid;
    refreshCartData(): Promise<void>;
    private renderGridCard;
    private handleAddToCart;
    goToSlide(i: number): void;
    syncDots(el: HTMLElement): void;
    startCheckout(): void;
    showGeoVerification(): void;
    setVerifiedLocation(loc: any): void;
    setOrderDelivery(delivery: any): void;
    showOrderSummary(): void;
    private showLoginPrompt;
}
